# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-mesh" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "ef0cff951686b9b2d97e0dc3522a7ae5163f31afeaf3ccc3ddd0aa825337b964"
      url "https://github.com/alpertarhan/agent-mesh/releases/download/v#{version}/agm_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "218a94ae891de21762f242267873dcdfcee8abe9bfdf335ec8991c6db2ea5649"
      url "https://github.com/alpertarhan/agent-mesh/releases/download/v#{version}/agm_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "240b4c01c9015778b884ae9a39ce50c347601a313acc0929f53dffc6eb760fb3"
      url "https://github.com/alpertarhan/agent-mesh/releases/download/v#{version}/agm_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d2294c34676a5974a9ed416b5d994f4c4d3e3f79e62ecd860f0923c46228552"
      url "https://github.com/alpertarhan/agent-mesh/releases/download/v#{version}/agm_linux_amd64.tar.gz"
    end
  end

  name "agent-mesh"
  desc "Local messaging between coding agents across harnesses"
  homepage "https://github.com/alpertarhan/agent-mesh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/agm"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `agm install` to set up (or update) the harness integrations.
  EOS
end
